### ISSUE TITLE
As a user I want to be able to use my microphone in order to talk to other participants in both the Game Room and the active Game session.

### ISSUE THREAD

**Issue by vichcruz** [sopra-fs24-group-25/SketchyPhone-Server#10]
### Acceptance Criteria
- [ ] At the start users can choose to enable/disable microphone input
- [ ] When first visiting the web-application, users are prompted with a permission prompt to use a user’s microphone.
- [ ] A user can find instructions on how to enable microphone permission if they revoked the permission at some point.

**Comment by guilloboi1917** [comment]
Not implemented
