### ISSUE TITLE
As a user I want to be able to use my accumulated votes to modulate other participant’s microphone output.

### ISSUE THREAD

**Issue by vichcruz** [sopra-fs24-group-25/SketchyPhone-Server#12]
### Acceptance Criteria
- [ ] A user can use their garnered votes to modify other participant’s microphone output.
- [ ] A user can choose between different audio effects (reverb, delay, chipmunk, robot voice, deep voice, time-modulated pitch)

**Comment by guilloboi1917** [comment]
Decided not to implement this feature (received OK from TA)
